### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/AddressesManager#17]
I merged in master branch of Enso today and updated with composer update.
AddressesManager package was not downloaded (it should be linked from Enso core).
Do I have to add it somewhere to composer.json?

**Comment by aocneanu** [comment]
It's not linked from Enso/core, but the main project.

just go with `composer require laravel-enso/addressesmanager`

**Comment by mauthi** [comment]
sorry, I accidently deleted one line in composer :(

**Comment by aocneanu** [comment]
so, this can be closed?

**Comment by mauthi** [comment]
yes, sorry!
