### ISSUE TITLE
Use a pre filled countries table

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/AddressesManager#18]
I use the following package to handle the countries table:
webpatser/laravel-countries

It provides a Seeder for a pre filled countries table (with a lot of additional information to each country).
Maybe it's interesting for you to change to this package?
Otherwise I have to find a solution to migrate your countries table to mine or vice versa.

**Comment by aocneanu** [comment]
i think that the country list is interesting. We'll look into it

**Comment by mauthi** [comment]
perfect, so I will wait with installation of AddressesManager until I get feedback.

**Comment by aocneanu** [comment]
@gandesc will modify the countries table and use the json from `laravel-countries` as a source.

**Comment by gandesc** [comment]
done! The package now uses `webpatser/laravel-countries`' list of countries

**Comment by mauthi** [comment]
Perfect - thx!
