### ISSUE TITLE
Query relating to seeding random addresses using factory

### ISSUE THREAD

**Issue by curtisdelicata** [laravel-enso/AddressesManager#29]
This is  a ** query **

### Prerequisites
* [Y ] Are you running the latest version?
* [Y ] Are you reporting to the correct repository?
* [Y ] Did you check the documentation?
* [Y] Did you perform a cursory search?

### Description

I am trying to seed random addresses to then assign to work orders. The trait requires me to use 

`<?php use App\User;

$factory->define(LaravelEnso\AddressesManager\app\Models\Address::class, function (Faker\Generator $faker) {

$user = User::find(1);
Auth::login($user);

 return [
        'addressable_type' => "App\WorkOrder",
        'addressable_id' => $faker->randomElement(\App\WorkOrder::pluck('id')->toArray()),
        'street' => $faker->name,
        'street_type' => 'Street',
        'number' => $faker->biasedNumberBetween($min = 0, $max = 140, $function = 'sqrt'),
        'postal_area' => $faker->postcode,
        'city' => $faker->city,
        'country_id' => 235,
        'created_by' => 1,
    ];
});
`
otherwise I get:
 `ErrorException  : Trying to get property 'id' of non-object

  at /vagrant/vendor/laravel-enso/trackwho/src/app/Traits/CreatedBy.php:10
     6| {
     7|     protected static function bootCreatedBy()
     8|     {
     9|         self::creating(function ($model) {
  > 10|             $model->created_by = auth()->user()->id;
    11|         });
    12|     }
    13| 
    14|     public function createdBy()

  Exception trace:

  1   Raven_Breadcrumbs_ErrorHandler::handleError("Trying to get property 'id' of non-object", "/vagrant/vendor/laravel-enso/trackwho/src/app/Traits/CreatedBy.php", [Object(LaravelEnso\AddressesManager\app\Models\Address)])
      /vagrant/vendor/laravel-enso/trackwho/src/app/Traits/CreatedBy.php:10

  2   LaravelEnso\AddressesManager\app\Models\Address::LaravelEnso\TrackWho\app\Traits\{closure}(Object(LaravelEnso\AddressesManager\app\Models\Address))
      /vagrant/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:360

`
### Expected behavior
Expected to happen as requires created by, but there must be a better way than me creating a user object? Can I bypass a trait? Is there a way to default created by to id 1?

**Comment by aocneanu** [comment]
What you did is the correct approach. You can't bypass the Trait.

You can also do `auth()->onceUsingId(1)` to save a query.

You don't have to fill the `created_by` because it will be done anyway in the trait.

But the real question is.. do we need the `created_by` field in the address? Because I really don't think it has any real uses. @gandesc , what's your opinion?

**Comment by curtisdelicata** [comment]
Thank you for your response.

**Comment by aocneanu** [comment]
the column was removed in removed in ef892ee2f11a59b692c253055f303278c02ecdde (v2.3.0). Run the helper command.
