### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by curtisdelicata** [laravel-enso/AddressesManager#34]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 74")
      /vagrant/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82

  2   PDOException::("SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 74")
      /vagrant/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80

**Comment by curtisdelicata** [comment]
Setting environment to testing bypasses this as it follows the function which limits to 10 countries.

Unsure which country has wrong column? JSON is validated as correct.

**Comment by aocneanu** [comment]
Hi Curtis,

It's fixed with 9b2714437dcce206340ca75702360dd3f3cb7359
